# development:
#   adapter: async

development:
  adapter: redis
  url: redis://localhost:6379/1

test:
  adapter: test

production:
  adapter: redis
  url: <%= ENV["REDISTOGO_URL"] %>
 # url: redis://redistogo:2fbda05393827c79d9b4d7a0d5e0b3af@tarpon.redistogo.com:10008/
 #      redis://redistogo:2fbda05393827c79d9b4d7a0d5e0b3af@tarpon.redistogo.com:10008/
  # url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  #redis://h:p8eb9fc5fdbd7c4e797749e8a88f84c8e31b2c3e707e9ca2e62f40de305785064@ec2-3-218-187-15.compute-1.amazonaws.com:19079